# Generated by Django 4.2.23 on 2025-08-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Consumed', 'Consumed'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('expiry_date', models.DateTimeField()),
                ('consumed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
